const cities = ["Paris", "New York", "Tokyo", "Sydney","Rome"];
cities.forEach(city => console.log(city.toUpperCase()));
let numbers = [1, 2, 3, 4, 5];
let squares = numbers.map(num => num * num);
console.log(squares);
const scores = [ 85, 42, 90, 75, 30, 100];
let highScores = scores.filter(score => score >= 80);
console.log(highScores);
const favoriteFoods = ["Pizza", "Sushi", "Tacos", "Pasta"];
const longNamesFood = favoriteFoods.find(food => food.length > 4);
const foodIndex = favoriteFoods.findIndex(food => food.length > 4);
console.log(longNamesFood);
console.log(foodIndex); 
const temperatures = [95, 68, 75, 80, 65];
const allAbove90 = temperatures.some(temp => temp > 90);
const anyAbove50 = temperatures.every(temp => temp > 50);
console.log(allAbove90);
console.log(anyAbove50);
const budget = 100;
const prices = [20, 30, 25, 10];
const totalCost = prices.reduce((total, price) => total -  price, budget);
console.log(totalCost);